import Gcd from './Gcd';
import nCr from './nCr';
import nCrs from './nCrs';
import nPr from './nPr';
import Pow from './Pow';
import Random from './Random';
import k from './k';
import Min from './Min';
import Max from './Max';
import Repetition from './Repetition';
import Lcm from './Lcm';
export { Gcd, nCr, nCrs, nPr, Pow, Random, k, Min, Max, Repetition, Lcm };
