import { Maths } from './FCC_modules/Modules/Math';
import { Html } from './FCC_modules/Modules/HTML';
import * as Ajax from './FCC_modules/Modules/Ajax';
import HelloWorld from './FCC_modules/Modules/HelloWorld';
import Gcd from './FCC_modules/Math/Gcd';
import k from './FCC_modules/Math/k';
import nCr from './FCC_modules/Math/nCr';
import nCrs from './FCC_modules/Math/nCrs';
import nPr from './FCC_modules/Math/nPr';
import Pow from './FCC_modules/Math/Pow';
import Random from './FCC_modules/Math/Random';
import Zeller from './FCC_modules/Props/Zeller';
import Zero from './FCC_modules/Props/Zero';
import cal from './FCC_modules/Props/calClass';
import error_language from './FCC_modules/Props/error_language';
import birthday from './FCC_modules/Props/Birthday';
import wait from './FCC_modules/Props/wait';
import render from './FCC_modules/Props/render';
import HeadUpperCase from "./FCC_modules/Props/HeadUpperCase";
import Hash from "./FCC_modules/Props/Hash";
import * as type from './FCC_modules/type/type';
const version = '1.0';
export { version, Maths, Html, Ajax, HelloWorld, Gcd, k, nCr, nCrs, nPr, Pow, Random, Zeller, Zero, cal, error_language, birthday, wait, render, HeadUpperCase, Hash, type };
